name: brilliant-auto-env
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - scikit-learn=1.4.2
  - dash=2.16.1
  - dash-bootstrap-components=1.6.0
  - plotly=5.21.0
  - jupyter=1.0.0