name: brilliant-auto-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - scikit-learn=1.6.1
  - scipy=1.13.0
  - dash=2.18.2
  - dash-bootstrap-components=1.7.1
  - plotly=6.1.0
  - jupyter=1.0.0
  - flask=3.1.1
  - apscheduler=3.11.0
  - boto3=1.38.18
  - joblib=1.3.2
  - p7zip=16.02
  - unzip=6.0
  - xgboost=2.0.3
  - pip
  - pip:
    - tensorflow==2.19.0
    - gdown==4.7.1
    - pytest==8.4.1
    - patool>=1.13